baseurl: /portal
name: Portal
description: Portal is the JavaScript library for real-time web application development
url: http://flowersinthesand.github.io/portal/
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - tables
    - with_toc_data
relative_permalinks: false
permalink: pretty